#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

title: Apache NLPCraft
copyright: Copyright 2021 (C) Apache Software Foundation.
baseurl: ""
url: ""

zip_base: apache-nlpcraft

twitter_username: nlpcraft
github_username:  nlpcraft

# Manually update to the latest version:
# ===================
latest_version: 0.9.0
java_client_latest_version: 0.9.0
# ===================

# SASS settings.
sass:
  sass_dir: _scss
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
  startings: [html, head, body]

minify_html: false

# Build settings.
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - apis/javadoc-0.6.2
  - apis/javadoc-0.5.0
  - apis/javadoc-0.7.0
  - apis/javadoc-0.7.1
  - apis/javadoc-0.7.2
  - apis/javadoc-0.7.3
  - apis/javadoc-0.7.4
  - apis/javadoc-0.7.5
  - apis/javadoc-0.8.0
  - apis/javadoc-0.9.0
  - .idea
  - _site

