pages = [{"l":"index.html#","e":false,"n":"NLPCraft","t":"NLPCraft","d":"","k":"static"},
{"l":"org/apache/nlpcraft.html#","e":false,"n":"org.apache.nlpcraft","t":"org.apache.nlpcraft","d":"org/apache/nlpcraft","k":"package"},
{"l":"org/apache/nlpcraft.html#===-ffffff15","e":false,"n":"===","t":"===(x: Option[T]): Boolean","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#===-fffffe7f","e":false,"n":"===","t":"===(x: T): Boolean","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#E-7a9","e":false,"n":"E","t":"E[T](msg: String, cause: Throwable): T","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#days-fffffbe0","e":false,"n":"days","t":"days: Int","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#days-fffff788","e":false,"n":"days","t":"days: Long","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#gb-fffffbe0","e":false,"n":"gb","t":"gb: Int","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#gb-fffff788","e":false,"n":"gb","t":"gb: Long","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#hours-fffffbe0","e":false,"n":"hours","t":"hours: Int","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#hours-fffff788","e":false,"n":"hours","t":"hours: Long","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#kb-fffffbe0","e":false,"n":"kb","t":"kb: Int","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#kb-fffff788","e":false,"n":"kb","t":"kb: Long","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#mb-fffffbe0","e":false,"n":"mb","t":"mb: Int","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#mb-fffff788","e":false,"n":"mb","t":"mb: Long","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#mins-fffffbe0","e":false,"n":"mins","t":"mins: Int","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#mins-fffff788","e":false,"n":"mins","t":"mins: Long","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#secs-fffffbe0","e":false,"n":"secs","t":"secs: Int","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#secs-fffff788","e":false,"n":"secs","t":"secs: Long","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#tb-fffffbe0","e":false,"n":"tb","t":"tb: Int","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft.html#tb-fffff788","e":false,"n":"tb","t":"tb: Long","d":"org/apache/nlpcraft","k":"def"},
{"l":"org/apache/nlpcraft/NCContext.html#","e":false,"n":"NCContext","t":"NCContext","d":"org/apache/nlpcraft/NCContext","k":"trait"},
{"l":"org/apache/nlpcraft/NCContext.html#getConversation-0","e":false,"n":"getConversation","t":"getConversation: NCConversation","d":"org/apache/nlpcraft/NCContext","k":"def"},
{"l":"org/apache/nlpcraft/NCContext.html#getModelConfig-0","e":false,"n":"getModelConfig","t":"getModelConfig: NCModelConfig","d":"org/apache/nlpcraft/NCContext","k":"def"},
{"l":"org/apache/nlpcraft/NCContext.html#getRequest-0","e":false,"n":"getRequest","t":"getRequest: NCRequest","d":"org/apache/nlpcraft/NCContext","k":"def"},
{"l":"org/apache/nlpcraft/NCContext.html#getTokens-0","e":false,"n":"getTokens","t":"getTokens: List[NCToken]","d":"org/apache/nlpcraft/NCContext","k":"def"},
{"l":"org/apache/nlpcraft/NCContext.html#getVariants-0","e":false,"n":"getVariants","t":"getVariants: List[NCVariant]","d":"org/apache/nlpcraft/NCContext","k":"def"},
{"l":"org/apache/nlpcraft/NCContext.html#isOwnerOf-fffff27e","e":false,"n":"isOwnerOf","t":"isOwnerOf(ent: NCEntity): Boolean","d":"org/apache/nlpcraft/NCContext","k":"def"},
{"l":"org/apache/nlpcraft/NCConversation.html#","e":false,"n":"NCConversation","t":"NCConversation","d":"org/apache/nlpcraft/NCConversation","k":"trait"},
{"l":"org/apache/nlpcraft/NCConversation.html#clearDialog-c9d","e":false,"n":"clearDialog","t":"clearDialog(filter: NCDialogFlowItem => Boolean): Unit","d":"org/apache/nlpcraft/NCConversation","k":"def"},
{"l":"org/apache/nlpcraft/NCConversation.html#clearStm-c9d","e":false,"n":"clearStm","t":"clearStm(filter: NCEntity => Boolean): Unit","d":"org/apache/nlpcraft/NCConversation","k":"def"},
{"l":"org/apache/nlpcraft/NCConversation.html#getData-0","e":false,"n":"getData","t":"getData: NCPropertyMap","d":"org/apache/nlpcraft/NCConversation","k":"def"},
{"l":"org/apache/nlpcraft/NCConversation.html#getDialogFlow-0","e":false,"n":"getDialogFlow","t":"getDialogFlow: List[NCDialogFlowItem]","d":"org/apache/nlpcraft/NCConversation","k":"def"},
{"l":"org/apache/nlpcraft/NCConversation.html#getStm-0","e":false,"n":"getStm","t":"getStm: List[NCEntity]","d":"org/apache/nlpcraft/NCConversation","k":"def"},
{"l":"org/apache/nlpcraft/NCCuration.html#","e":false,"n":"NCCuration","t":"NCCuration(msg: String, cause: Throwable) extends NCRejection","d":"org/apache/nlpcraft/NCCuration","k":"class"},
{"l":"org/apache/nlpcraft/NCDialogFlowItem.html#","e":false,"n":"NCDialogFlowItem","t":"NCDialogFlowItem","d":"org/apache/nlpcraft/NCDialogFlowItem","k":"trait"},
{"l":"org/apache/nlpcraft/NCDialogFlowItem.html#getIntentMatch-0","e":false,"n":"getIntentMatch","t":"getIntentMatch: NCIntentMatch","d":"org/apache/nlpcraft/NCDialogFlowItem","k":"def"},
{"l":"org/apache/nlpcraft/NCDialogFlowItem.html#getRequest-0","e":false,"n":"getRequest","t":"getRequest: NCRequest","d":"org/apache/nlpcraft/NCDialogFlowItem","k":"def"},
{"l":"org/apache/nlpcraft/NCDialogFlowItem.html#getResult-0","e":false,"n":"getResult","t":"getResult: Option[NCResult]","d":"org/apache/nlpcraft/NCDialogFlowItem","k":"def"},
{"l":"org/apache/nlpcraft/NCEntity.html#","e":false,"n":"NCEntity","t":"NCEntity extends NCPropertyMap","d":"org/apache/nlpcraft/NCEntity","k":"trait"},
{"l":"org/apache/nlpcraft/NCEntity.html#getGroups-0","e":false,"n":"getGroups","t":"getGroups: Set[String]","d":"org/apache/nlpcraft/NCEntity","k":"def"},
{"l":"org/apache/nlpcraft/NCEntity.html#getId-0","e":false,"n":"getId","t":"getId: String","d":"org/apache/nlpcraft/NCEntity","k":"def"},
{"l":"org/apache/nlpcraft/NCEntity.html#getRequestId-0","e":false,"n":"getRequestId","t":"getRequestId: String","d":"org/apache/nlpcraft/NCEntity","k":"def"},
{"l":"org/apache/nlpcraft/NCEntity.html#getTokens-0","e":false,"n":"getTokens","t":"getTokens: List[NCToken]","d":"org/apache/nlpcraft/NCEntity","k":"def"},
{"l":"org/apache/nlpcraft/NCEntity.html#mkText-0","e":false,"n":"mkText","t":"mkText: String","d":"org/apache/nlpcraft/NCEntity","k":"def"},
{"l":"org/apache/nlpcraft/NCEntityEnricher.html#","e":false,"n":"NCEntityEnricher","t":"NCEntityEnricher extends NCLifecycle","d":"org/apache/nlpcraft/NCEntityEnricher","k":"trait"},
{"l":"org/apache/nlpcraft/NCEntityEnricher.html#enrich-7e2","e":false,"n":"enrich","t":"enrich(req: NCRequest, cfg: NCModelConfig, ents: List[NCEntity]): Unit","d":"org/apache/nlpcraft/NCEntityEnricher","k":"def"},
{"l":"org/apache/nlpcraft/NCEntityMapper.html#","e":false,"n":"NCEntityMapper","t":"NCEntityMapper extends NCLifecycle","d":"org/apache/nlpcraft/NCEntityMapper","k":"trait"},
{"l":"org/apache/nlpcraft/NCEntityMapper.html#map-fffff77c","e":false,"n":"map","t":"map(req: NCRequest, cfg: NCModelConfig, ents: List[NCEntity]): List[NCEntity]","d":"org/apache/nlpcraft/NCEntityMapper","k":"def"},
{"l":"org/apache/nlpcraft/NCEntityParser.html#","e":false,"n":"NCEntityParser","t":"NCEntityParser extends NCLifecycle","d":"org/apache/nlpcraft/NCEntityParser","k":"trait"},
{"l":"org/apache/nlpcraft/NCEntityParser.html#parse-fffff77c","e":false,"n":"parse","t":"parse(req: NCRequest, cfg: NCModelConfig, toks: List[NCToken]): List[NCEntity]","d":"org/apache/nlpcraft/NCEntityParser","k":"def"},
{"l":"org/apache/nlpcraft/NCEntityValidator.html#","e":false,"n":"NCEntityValidator","t":"NCEntityValidator extends NCLifecycle","d":"org/apache/nlpcraft/NCEntityValidator","k":"trait"},
{"l":"org/apache/nlpcraft/NCEntityValidator.html#validate-7e2","e":false,"n":"validate","t":"validate(req: NCRequest, cfg: NCModelConfig, ents: List[NCEntity]): Unit","d":"org/apache/nlpcraft/NCEntityValidator","k":"def"},
{"l":"org/apache/nlpcraft/NCException.html#","e":false,"n":"NCException","t":"NCException(msg: String, cause: Throwable) extends RuntimeException","d":"org/apache/nlpcraft/NCException","k":"class"},
{"l":"org/apache/nlpcraft/NCIntentMatch.html#","e":false,"n":"NCIntentMatch","t":"NCIntentMatch","d":"org/apache/nlpcraft/NCIntentMatch","k":"trait"},
{"l":"org/apache/nlpcraft/NCIntentMatch.html#getIntentEntities-0","e":false,"n":"getIntentEntities","t":"getIntentEntities: List[List[NCEntity]]","d":"org/apache/nlpcraft/NCIntentMatch","k":"def"},
{"l":"org/apache/nlpcraft/NCIntentMatch.html#getIntentId-0","e":false,"n":"getIntentId","t":"getIntentId: String","d":"org/apache/nlpcraft/NCIntentMatch","k":"def"},
{"l":"org/apache/nlpcraft/NCIntentMatch.html#getTermEntities-fffff84b","e":false,"n":"getTermEntities","t":"getTermEntities(idx: Int): List[NCEntity]","d":"org/apache/nlpcraft/NCIntentMatch","k":"def"},
{"l":"org/apache/nlpcraft/NCIntentMatch.html#getTermEntities-94d","e":false,"n":"getTermEntities","t":"getTermEntities(termId: String): List[NCEntity]","d":"org/apache/nlpcraft/NCIntentMatch","k":"def"},
{"l":"org/apache/nlpcraft/NCIntentMatch.html#getVariant-0","e":false,"n":"getVariant","t":"getVariant: NCVariant","d":"org/apache/nlpcraft/NCIntentMatch","k":"def"},
{"l":"org/apache/nlpcraft/NCIntentSkip.html#","e":false,"n":"NCIntentSkip","t":"NCIntentSkip(msg: String, cause: Throwable) extends NCException","d":"org/apache/nlpcraft/NCIntentSkip","k":"class"},
{"l":"org/apache/nlpcraft/NCLifecycle.html#","e":false,"n":"NCLifecycle","t":"NCLifecycle","d":"org/apache/nlpcraft/NCLifecycle","k":"trait"},
{"l":"org/apache/nlpcraft/NCLifecycle.html#onStart-fffff138","e":false,"n":"onStart","t":"onStart(cfg: NCModelConfig): Unit","d":"org/apache/nlpcraft/NCLifecycle","k":"def"},
{"l":"org/apache/nlpcraft/NCLifecycle.html#onStop-fffff138","e":false,"n":"onStop","t":"onStop(cfg: NCModelConfig): Unit","d":"org/apache/nlpcraft/NCLifecycle","k":"def"},
{"l":"org/apache/nlpcraft/NCMatchedCallback.html#","e":false,"n":"NCMatchedCallback","t":"NCMatchedCallback","d":"org/apache/nlpcraft/NCMatchedCallback","k":"trait"},
{"l":"org/apache/nlpcraft/NCMatchedCallback.html#getCallback-0","e":false,"n":"getCallback","t":"getCallback: List[List[NCEntity]] => NCResult","d":"org/apache/nlpcraft/NCMatchedCallback","k":"def"},
{"l":"org/apache/nlpcraft/NCMatchedCallback.html#getCallbackArguments-0","e":false,"n":"getCallbackArguments","t":"getCallbackArguments: List[List[NCEntity]]","d":"org/apache/nlpcraft/NCMatchedCallback","k":"def"},
{"l":"org/apache/nlpcraft/NCMatchedCallback.html#getIntentId-0","e":false,"n":"getIntentId","t":"getIntentId: String","d":"org/apache/nlpcraft/NCMatchedCallback","k":"def"},
{"l":"org/apache/nlpcraft/NCModel.html#","e":false,"n":"NCModel","t":"NCModel","d":"org/apache/nlpcraft/NCModel","k":"trait"},
{"l":"org/apache/nlpcraft/NCModel.html#getConfig-0","e":false,"n":"getConfig","t":"getConfig: NCModelConfig","d":"org/apache/nlpcraft/NCModel","k":"def"},
{"l":"org/apache/nlpcraft/NCModel.html#getPipeline-0","e":false,"n":"getPipeline","t":"getPipeline: NCPipeline","d":"org/apache/nlpcraft/NCModel","k":"def"},
{"l":"org/apache/nlpcraft/NCModel.html#onContext-38d","e":false,"n":"onContext","t":"onContext(ctx: NCContext): Option[NCResult]","d":"org/apache/nlpcraft/NCModel","k":"def"},
{"l":"org/apache/nlpcraft/NCModel.html#onError-fffff759","e":false,"n":"onError","t":"onError(ctx: NCContext, e: Throwable): Option[NCResult]","d":"org/apache/nlpcraft/NCModel","k":"def"},
{"l":"org/apache/nlpcraft/NCModel.html#onMatchedIntent-946","e":false,"n":"onMatchedIntent","t":"onMatchedIntent(ctx: NCContext, im: NCIntentMatch): Boolean","d":"org/apache/nlpcraft/NCModel","k":"def"},
{"l":"org/apache/nlpcraft/NCModel.html#onRejection-4fa","e":false,"n":"onRejection","t":"onRejection(ctx: NCContext, im: Option[NCIntentMatch], e: NCRejection): Option[NCResult]","d":"org/apache/nlpcraft/NCModel","k":"def"},
{"l":"org/apache/nlpcraft/NCModel.html#onResult-fffffaf3","e":false,"n":"onResult","t":"onResult(ctx: NCContext, im: NCIntentMatch, res: NCResult): Option[NCResult]","d":"org/apache/nlpcraft/NCModel","k":"def"},
{"l":"org/apache/nlpcraft/NCModelAdapter.html#","e":false,"n":"NCModelAdapter","t":"NCModelAdapter(cfg: NCModelConfig, pipeline: NCPipeline) extends NCModel","d":"org/apache/nlpcraft/NCModelAdapter","k":"class"},
{"l":"org/apache/nlpcraft/NCModelClient.html#","e":false,"n":"NCModelClient","t":"NCModelClient(mdl: NCModel) extends LazyLogging with AutoCloseable","d":"org/apache/nlpcraft/NCModelClient","k":"class"},
{"l":"org/apache/nlpcraft/NCModelClient.html#ask-fffff9ce","e":false,"n":"ask","t":"ask(txt: String, usrId: String, data: Map[String, AnyRef]): NCResult","d":"org/apache/nlpcraft/NCModelClient","k":"def"},
{"l":"org/apache/nlpcraft/NCModelClient.html#clearDialog-571","e":false,"n":"clearDialog","t":"clearDialog(usrId: String): Unit","d":"org/apache/nlpcraft/NCModelClient","k":"def"},
{"l":"org/apache/nlpcraft/NCModelClient.html#clearDialog-1d8","e":false,"n":"clearDialog","t":"clearDialog(usrId: String, filter: NCDialogFlowItem => Boolean): Unit","d":"org/apache/nlpcraft/NCModelClient","k":"def"},
{"l":"org/apache/nlpcraft/NCModelClient.html#clearStm-571","e":false,"n":"clearStm","t":"clearStm(usrId: String): Unit","d":"org/apache/nlpcraft/NCModelClient","k":"def"},
{"l":"org/apache/nlpcraft/NCModelClient.html#clearStm-1d8","e":false,"n":"clearStm","t":"clearStm(usrId: String, filter: NCEntity => Boolean): Unit","d":"org/apache/nlpcraft/NCModelClient","k":"def"},
{"l":"org/apache/nlpcraft/NCModelClient.html#debugAsk-fffff96c","e":false,"n":"debugAsk","t":"debugAsk(txt: String, usrId: String, saveHist: Boolean, data: Map[String, AnyRef]): NCMatchedCallback","d":"org/apache/nlpcraft/NCModelClient","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig$.html#","e":false,"n":"NCModelConfig","t":"NCModelConfig","d":"org/apache/nlpcraft/NCModelConfig$","k":"object"},
{"l":"org/apache/nlpcraft/NCModelConfig$.html#DFLT_CONV_DEPTH-0","e":false,"n":"DFLT_CONV_DEPTH","t":"DFLT_CONV_DEPTH: Int","d":"org/apache/nlpcraft/NCModelConfig$","k":"val"},
{"l":"org/apache/nlpcraft/NCModelConfig$.html#DFLT_CONV_TIMEOUT-0","e":false,"n":"DFLT_CONV_TIMEOUT","t":"DFLT_CONV_TIMEOUT: Long","d":"org/apache/nlpcraft/NCModelConfig$","k":"val"},
{"l":"org/apache/nlpcraft/NCModelConfig$.html#apply-b9d","e":false,"n":"apply","t":"apply(id: String, name: String, ver: String): NCModelConfig","d":"org/apache/nlpcraft/NCModelConfig$","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig$.html#apply-613","e":false,"n":"apply","t":"apply(id: String, name: String, ver: String, desc: String, orig: String): NCModelConfig","d":"org/apache/nlpcraft/NCModelConfig$","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig$.html#apply-362","e":false,"n":"apply","t":"apply(id: String, name: String, ver: String, desc: String, orig: String, convTimeout: Long, convDepth: Int): NCModelConfig","d":"org/apache/nlpcraft/NCModelConfig$","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig.html#","e":false,"n":"NCModelConfig","t":"NCModelConfig extends NCPropertyMapAdapter","d":"org/apache/nlpcraft/NCModelConfig","k":"trait"},
{"l":"org/apache/nlpcraft/NCModelConfig.html#getConversationDepth-0","e":false,"n":"getConversationDepth","t":"getConversationDepth: Int","d":"org/apache/nlpcraft/NCModelConfig","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig.html#getConversationTimeout-0","e":false,"n":"getConversationTimeout","t":"getConversationTimeout: Long","d":"org/apache/nlpcraft/NCModelConfig","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig.html#getDescription-0","e":false,"n":"getDescription","t":"getDescription: Option[String]","d":"org/apache/nlpcraft/NCModelConfig","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig.html#getId-0","e":false,"n":"getId","t":"getId: String","d":"org/apache/nlpcraft/NCModelConfig","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig.html#getName-0","e":false,"n":"getName","t":"getName: String","d":"org/apache/nlpcraft/NCModelConfig","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig.html#getOrigin-0","e":false,"n":"getOrigin","t":"getOrigin: Option[String]","d":"org/apache/nlpcraft/NCModelConfig","k":"def"},
{"l":"org/apache/nlpcraft/NCModelConfig.html#getVersion-0","e":false,"n":"getVersion","t":"getVersion: String","d":"org/apache/nlpcraft/NCModelConfig","k":"def"},
{"l":"org/apache/nlpcraft/NCPipeline.html#","e":false,"n":"NCPipeline","t":"NCPipeline","d":"org/apache/nlpcraft/NCPipeline","k":"trait"},
{"l":"org/apache/nlpcraft/NCPipeline.html#getEntityEnrichers-0","e":false,"n":"getEntityEnrichers","t":"getEntityEnrichers: List[NCEntityEnricher]","d":"org/apache/nlpcraft/NCPipeline","k":"def"},
{"l":"org/apache/nlpcraft/NCPipeline.html#getEntityMappers-0","e":false,"n":"getEntityMappers","t":"getEntityMappers: List[NCEntityMapper]","d":"org/apache/nlpcraft/NCPipeline","k":"def"},
{"l":"org/apache/nlpcraft/NCPipeline.html#getEntityParsers-0","e":false,"n":"getEntityParsers","t":"getEntityParsers: List[NCEntityParser]","d":"org/apache/nlpcraft/NCPipeline","k":"def"},
{"l":"org/apache/nlpcraft/NCPipeline.html#getEntityValidators-0","e":false,"n":"getEntityValidators","t":"getEntityValidators: List[NCEntityValidator]","d":"org/apache/nlpcraft/NCPipeline","k":"def"},
{"l":"org/apache/nlpcraft/NCPipeline.html#getTokenEnrichers-0","e":false,"n":"getTokenEnrichers","t":"getTokenEnrichers: List[NCTokenEnricher]","d":"org/apache/nlpcraft/NCPipeline","k":"def"},
{"l":"org/apache/nlpcraft/NCPipeline.html#getTokenParser-0","e":false,"n":"getTokenParser","t":"getTokenParser: NCTokenParser","d":"org/apache/nlpcraft/NCPipeline","k":"def"},
{"l":"org/apache/nlpcraft/NCPipeline.html#getTokenValidators-0","e":false,"n":"getTokenValidators","t":"getTokenValidators: List[NCTokenValidator]","d":"org/apache/nlpcraft/NCPipeline","k":"def"},
{"l":"org/apache/nlpcraft/NCPipeline.html#getVariantFilter-0","e":false,"n":"getVariantFilter","t":"getVariantFilter: Option[NCVariantFilter]","d":"org/apache/nlpcraft/NCPipeline","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#","e":false,"n":"NCPipelineBuilder","t":"NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"class"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#build-0","e":false,"n":"build","t":"build: NCPipeline","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withEntityEnricher-b06","e":false,"n":"withEntityEnricher","t":"withEntityEnricher(entEnricher: NCEntityEnricher): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withEntityEnrichers-28","e":false,"n":"withEntityEnrichers","t":"withEntityEnrichers(entEnrichers: List[NCEntityEnricher]): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withEntityMapper-fffff217","e":false,"n":"withEntityMapper","t":"withEntityMapper(entMapper: NCEntityMapper): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withEntityMappers-28","e":false,"n":"withEntityMappers","t":"withEntityMappers(entMappers: List[NCEntityMapper]): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withEntityParser-fffff6f9","e":false,"n":"withEntityParser","t":"withEntityParser(entParser: NCEntityParser): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withEntityParsers-28","e":false,"n":"withEntityParsers","t":"withEntityParsers(entParsers: List[NCEntityParser]): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withEntityValidator-fffffdea","e":false,"n":"withEntityValidator","t":"withEntityValidator(entVal: NCEntityValidator): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withEntityValidators-28","e":false,"n":"withEntityValidators","t":"withEntityValidators(entVals: List[NCEntityValidator]): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withSemantic-fffff475","e":false,"n":"withSemantic","t":"withSemantic(lang: String, macros: Map[String, String], elms: List[NCSemanticElement]): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withSemantic-fffff40d","e":false,"n":"withSemantic","t":"withSemantic(lang: String, elms: List[NCSemanticElement]): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withSemantic-fffff4b0","e":false,"n":"withSemantic","t":"withSemantic(lang: String, mdlSrc: String): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withTokenEnricher-fffff44e","e":false,"n":"withTokenEnricher","t":"withTokenEnricher(tokEnricher: NCTokenEnricher): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withTokenEnrichers-28","e":false,"n":"withTokenEnrichers","t":"withTokenEnrichers(tokEnrichers: List[NCTokenEnricher]): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withTokenParser-241","e":false,"n":"withTokenParser","t":"withTokenParser(tokParser: NCTokenParser): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withTokenValidator-da2","e":false,"n":"withTokenValidator","t":"withTokenValidator(tokVal: NCTokenValidator): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withTokenValidators-28","e":false,"n":"withTokenValidators","t":"withTokenValidators(tokVals: List[NCTokenValidator]): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPipelineBuilder.html#withVariantFilter-fffffcbc","e":false,"n":"withVariantFilter","t":"withVariantFilter(varFilter: NCVariantFilter): NCPipelineBuilder","d":"org/apache/nlpcraft/NCPipelineBuilder","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#","e":false,"n":"NCPropertyMap","t":"NCPropertyMap","d":"org/apache/nlpcraft/NCPropertyMap","k":"trait"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#apply-229","e":false,"n":"apply","t":"apply[T](key: String): T","d":"org/apache/nlpcraft/NCPropertyMap","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#clear-94c","e":false,"n":"clear","t":"clear(): Unit","d":"org/apache/nlpcraft/NCPropertyMap","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#contains-fffffd1b","e":false,"n":"contains","t":"contains(key: String): Boolean","d":"org/apache/nlpcraft/NCPropertyMap","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#get-fffff9d3","e":false,"n":"get","t":"get[T](key: String): Option[T]","d":"org/apache/nlpcraft/NCPropertyMap","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#keysSet-0","e":false,"n":"keysSet","t":"keysSet: Set[String]","d":"org/apache/nlpcraft/NCPropertyMap","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#put-9bc","e":false,"n":"put","t":"put[T](key: String, obj: Any): T","d":"org/apache/nlpcraft/NCPropertyMap","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#putIfAbsent-9bc","e":false,"n":"putIfAbsent","t":"putIfAbsent[T](key: String, obj: T): T","d":"org/apache/nlpcraft/NCPropertyMap","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#remove-229","e":false,"n":"remove","t":"remove[T](key: String): T","d":"org/apache/nlpcraft/NCPropertyMap","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMap.html#remove-fffff468","e":false,"n":"remove","t":"remove(key: String, obj: Any): Boolean","d":"org/apache/nlpcraft/NCPropertyMap","k":"def"},
{"l":"org/apache/nlpcraft/NCPropertyMapAdapter.html#","e":false,"n":"NCPropertyMapAdapter","t":"NCPropertyMapAdapter extends NCPropertyMap","d":"org/apache/nlpcraft/NCPropertyMapAdapter","k":"class"},
{"l":"org/apache/nlpcraft/NCRejection.html#","e":false,"n":"NCRejection","t":"NCRejection(msg: String, cause: Throwable) extends RuntimeException","d":"org/apache/nlpcraft/NCRejection","k":"class"},
{"l":"org/apache/nlpcraft/NCRequest.html#","e":false,"n":"NCRequest","t":"NCRequest","d":"org/apache/nlpcraft/NCRequest","k":"trait"},
{"l":"org/apache/nlpcraft/NCRequest.html#getReceiveTimestamp-0","e":false,"n":"getReceiveTimestamp","t":"getReceiveTimestamp: Long","d":"org/apache/nlpcraft/NCRequest","k":"def"},
{"l":"org/apache/nlpcraft/NCRequest.html#getRequestData-0","e":false,"n":"getRequestData","t":"getRequestData: Map[String, Any]","d":"org/apache/nlpcraft/NCRequest","k":"def"},
{"l":"org/apache/nlpcraft/NCRequest.html#getRequestId-0","e":false,"n":"getRequestId","t":"getRequestId: String","d":"org/apache/nlpcraft/NCRequest","k":"def"},
{"l":"org/apache/nlpcraft/NCRequest.html#getText-0","e":false,"n":"getText","t":"getText: String","d":"org/apache/nlpcraft/NCRequest","k":"def"},
{"l":"org/apache/nlpcraft/NCRequest.html#getUserId-0","e":false,"n":"getUserId","t":"getUserId: String","d":"org/apache/nlpcraft/NCRequest","k":"def"},
{"l":"org/apache/nlpcraft/NCResult$.html#","e":false,"n":"NCResult","t":"NCResult","d":"org/apache/nlpcraft/NCResult$","k":"object"},
{"l":"org/apache/nlpcraft/NCResult$.html#apply-70a","e":false,"n":"apply","t":"apply(body: Any, resultType: NCResultType, intentId: String): NCResult","d":"org/apache/nlpcraft/NCResult$","k":"def"},
{"l":"org/apache/nlpcraft/NCResult$.html#apply-fffffc25","e":false,"n":"apply","t":"apply(body: Any, resultType: NCResultType): NCResult","d":"org/apache/nlpcraft/NCResult$","k":"def"},
{"l":"org/apache/nlpcraft/NCResult$.html#apply-f6f","e":false,"n":"apply","t":"apply(body: Any): NCResult","d":"org/apache/nlpcraft/NCResult$","k":"def"},
{"l":"org/apache/nlpcraft/NCResult.html#","e":false,"n":"NCResult","t":"NCResult","d":"org/apache/nlpcraft/NCResult","k":"trait"},
{"l":"org/apache/nlpcraft/NCResult.html#getBody-0","e":false,"n":"getBody","t":"getBody: Any","d":"org/apache/nlpcraft/NCResult","k":"def"},
{"l":"org/apache/nlpcraft/NCResult.html#getIntentId-0","e":false,"n":"getIntentId","t":"getIntentId: Option[String]","d":"org/apache/nlpcraft/NCResult","k":"def"},
{"l":"org/apache/nlpcraft/NCResult.html#getType-0","e":false,"n":"getType","t":"getType: NCResultType","d":"org/apache/nlpcraft/NCResult","k":"def"},
{"l":"org/apache/nlpcraft/NCResultType.html#","e":false,"n":"NCResultType","t":"NCResultType","d":"org/apache/nlpcraft/NCResultType","k":"enum"},
{"l":"org/apache/nlpcraft/NCResultType.html#ASK_RESULT-0","e":false,"n":"ASK_RESULT","t":"ASK_RESULT extends NCResultType","d":"org/apache/nlpcraft/NCResultType","k":"case"},
{"l":"org/apache/nlpcraft/NCResultType.html#ASK_DIALOG-0","e":false,"n":"ASK_DIALOG","t":"ASK_DIALOG extends NCResultType","d":"org/apache/nlpcraft/NCResultType","k":"case"},
{"l":"org/apache/nlpcraft/NCToken.html#","e":false,"n":"NCToken","t":"NCToken extends NCPropertyMap","d":"org/apache/nlpcraft/NCToken","k":"trait"},
{"l":"org/apache/nlpcraft/NCToken.html#getEndCharIndex-0","e":false,"n":"getEndCharIndex","t":"getEndCharIndex: Int","d":"org/apache/nlpcraft/NCToken","k":"def"},
{"l":"org/apache/nlpcraft/NCToken.html#getIndex-0","e":false,"n":"getIndex","t":"getIndex: Int","d":"org/apache/nlpcraft/NCToken","k":"def"},
{"l":"org/apache/nlpcraft/NCToken.html#getStartCharIndex-0","e":false,"n":"getStartCharIndex","t":"getStartCharIndex: Int","d":"org/apache/nlpcraft/NCToken","k":"def"},
{"l":"org/apache/nlpcraft/NCToken.html#getText-0","e":false,"n":"getText","t":"getText: String","d":"org/apache/nlpcraft/NCToken","k":"def"},
{"l":"org/apache/nlpcraft/NCTokenEnricher.html#","e":false,"n":"NCTokenEnricher","t":"NCTokenEnricher extends NCLifecycle","d":"org/apache/nlpcraft/NCTokenEnricher","k":"trait"},
{"l":"org/apache/nlpcraft/NCTokenEnricher.html#enrich-7e2","e":false,"n":"enrich","t":"enrich(req: NCRequest, cfg: NCModelConfig, toks: List[NCToken]): Unit","d":"org/apache/nlpcraft/NCTokenEnricher","k":"def"},
{"l":"org/apache/nlpcraft/NCTokenParser.html#","e":false,"n":"NCTokenParser","t":"NCTokenParser","d":"org/apache/nlpcraft/NCTokenParser","k":"trait"},
{"l":"org/apache/nlpcraft/NCTokenParser.html#tokenize-94d","e":false,"n":"tokenize","t":"tokenize(text: String): List[NCToken]","d":"org/apache/nlpcraft/NCTokenParser","k":"def"},
{"l":"org/apache/nlpcraft/NCTokenValidator.html#","e":false,"n":"NCTokenValidator","t":"NCTokenValidator extends NCLifecycle","d":"org/apache/nlpcraft/NCTokenValidator","k":"trait"},
{"l":"org/apache/nlpcraft/NCTokenValidator.html#validate-7e2","e":false,"n":"validate","t":"validate(req: NCRequest, cfg: NCModelConfig, toks: List[NCToken]): Unit","d":"org/apache/nlpcraft/NCTokenValidator","k":"def"},
{"l":"org/apache/nlpcraft/NCVariant.html#","e":false,"n":"NCVariant","t":"NCVariant","d":"org/apache/nlpcraft/NCVariant","k":"trait"},
{"l":"org/apache/nlpcraft/NCVariant.html#getEntities-0","e":false,"n":"getEntities","t":"getEntities: List[NCEntity]","d":"org/apache/nlpcraft/NCVariant","k":"def"},
{"l":"org/apache/nlpcraft/NCVariantFilter.html#","e":false,"n":"NCVariantFilter","t":"NCVariantFilter extends NCLifecycle","d":"org/apache/nlpcraft/NCVariantFilter","k":"trait"},
{"l":"org/apache/nlpcraft/NCVariantFilter.html#filter-fffff77c","e":false,"n":"filter","t":"filter(req: NCRequest, cfg: NCModelConfig, vars: List[NCVariant]): List[NCVariant]","d":"org/apache/nlpcraft/NCVariantFilter","k":"def"},
{"l":"org/apache/nlpcraft/nlp/enrichers.html#","e":false,"n":"org.apache.nlpcraft.nlp.enrichers","t":"org.apache.nlpcraft.nlp.enrichers","d":"org/apache/nlpcraft/nlp/enrichers","k":"package"},
{"l":"org/apache/nlpcraft/nlp/enrichers/NCEnBracketsTokenEnricher.html#","e":false,"n":"NCEnBracketsTokenEnricher","t":"NCEnBracketsTokenEnricher extends NCTokenEnricher with LazyLogging","d":"org/apache/nlpcraft/nlp/enrichers/NCEnBracketsTokenEnricher","k":"class"},
{"l":"org/apache/nlpcraft/nlp/enrichers/NCEnDictionaryTokenEnricher.html#","e":false,"n":"NCEnDictionaryTokenEnricher","t":"NCEnDictionaryTokenEnricher extends NCTokenEnricher","d":"org/apache/nlpcraft/nlp/enrichers/NCEnDictionaryTokenEnricher","k":"class"},
{"l":"org/apache/nlpcraft/nlp/enrichers/NCEnQuotesTokenEnricher.html#","e":false,"n":"NCEnQuotesTokenEnricher","t":"NCEnQuotesTokenEnricher extends NCTokenEnricher with LazyLogging","d":"org/apache/nlpcraft/nlp/enrichers/NCEnQuotesTokenEnricher","k":"class"},
{"l":"org/apache/nlpcraft/nlp/enrichers/NCEnStopWordsTokenEnricher$.html#","e":false,"n":"NCEnStopWordsTokenEnricher","t":"NCEnStopWordsTokenEnricher","d":"org/apache/nlpcraft/nlp/enrichers/NCEnStopWordsTokenEnricher$","k":"object"},
{"l":"org/apache/nlpcraft/nlp/enrichers/NCEnStopWordsTokenEnricher$.html#Wildcard-0","e":false,"n":"Wildcard","t":"Wildcard = (String, String)","d":"org/apache/nlpcraft/nlp/enrichers/NCEnStopWordsTokenEnricher$","k":"type"},
{"l":"org/apache/nlpcraft/nlp/enrichers/NCEnStopWordsTokenEnricher$.html#Word-0","e":false,"n":"Word","t":"Word = String","d":"org/apache/nlpcraft/nlp/enrichers/NCEnStopWordsTokenEnricher$","k":"type"},
{"l":"org/apache/nlpcraft/nlp/enrichers/NCEnStopWordsTokenEnricher.html#","e":false,"n":"NCEnStopWordsTokenEnricher","t":"NCEnStopWordsTokenEnricher(addStopsSet: Set[String], exclStopsSet: Set[String]) extends NCTokenEnricher with LazyLogging","d":"org/apache/nlpcraft/nlp/enrichers/NCEnStopWordsTokenEnricher","k":"class"},
{"l":"org/apache/nlpcraft/nlp/enrichers/NCEnSwearWordsTokenEnricher.html#","e":false,"n":"NCEnSwearWordsTokenEnricher","t":"NCEnSwearWordsTokenEnricher(res: String) extends NCTokenEnricher with LazyLogging","d":"org/apache/nlpcraft/nlp/enrichers/NCEnSwearWordsTokenEnricher","k":"class"},
{"l":"org/apache/nlpcraft/nlp/enrichers/NCOpenNLPLemmaPosTokenEnricher.html#","e":false,"n":"NCOpenNLPLemmaPosTokenEnricher","t":"NCOpenNLPLemmaPosTokenEnricher(posMdlSrc: String, lemmaDicSrc: String) extends NCTokenEnricher with LazyLogging","d":"org/apache/nlpcraft/nlp/enrichers/NCOpenNLPLemmaPosTokenEnricher","k":"class"},
{"l":"org/apache/nlpcraft/nlp/parsers.html#","e":false,"n":"org.apache.nlpcraft.nlp.parsers","t":"org.apache.nlpcraft.nlp.parsers","d":"org/apache/nlpcraft/nlp/parsers","k":"package"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCNLPEntityParser$.html#","e":false,"n":"NCNLPEntityParser","t":"NCNLPEntityParser","d":"org/apache/nlpcraft/nlp/parsers/NCNLPEntityParser$","k":"object"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCNLPEntityParser.html#","e":false,"n":"NCNLPEntityParser","t":"NCNLPEntityParser(predicate: NCToken => Boolean) extends NCEntityParser","d":"org/apache/nlpcraft/nlp/parsers/NCNLPEntityParser","k":"class"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCOpenNLPEntityParser$.html#","e":false,"n":"NCOpenNLPEntityParser","t":"NCOpenNLPEntityParser","d":"org/apache/nlpcraft/nlp/parsers/NCOpenNLPEntityParser$","k":"object"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCOpenNLPEntityParser$.html#apply-fffffcf0","e":false,"n":"apply","t":"apply(src: String): NCOpenNLPEntityParser","d":"org/apache/nlpcraft/nlp/parsers/NCOpenNLPEntityParser$","k":"def"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCOpenNLPEntityParser.html#","e":false,"n":"NCOpenNLPEntityParser","t":"NCOpenNLPEntityParser(srcs: List[String]) extends NCEntityParser with LazyLogging","d":"org/apache/nlpcraft/nlp/parsers/NCOpenNLPEntityParser","k":"class"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCOpenNLPTokenParser.html#","e":false,"n":"NCOpenNLPTokenParser","t":"NCOpenNLPTokenParser(tokMdl: String) extends NCTokenParser with LazyLogging","d":"org/apache/nlpcraft/nlp/parsers/NCOpenNLPTokenParser","k":"class"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement.html#","e":false,"n":"NCSemanticElement","t":"NCSemanticElement","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement","k":"trait"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement.html#getGroups-0","e":false,"n":"getGroups","t":"getGroups: Set[String]","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement","k":"def"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement.html#getId-0","e":false,"n":"getId","t":"getId: String","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement","k":"def"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement.html#getProperties-0","e":false,"n":"getProperties","t":"getProperties: Map[String, AnyRef]","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement","k":"def"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement.html#getSynonyms-0","e":false,"n":"getSynonyms","t":"getSynonyms: Set[String]","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement","k":"def"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement.html#getValues-0","e":false,"n":"getValues","t":"getValues: Map[String, Set[String]]","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticElement","k":"def"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser$.html#","e":false,"n":"NCSemanticEntityParser","t":"NCSemanticEntityParser","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser$","k":"object"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser$.html#apply-1e4","e":false,"n":"apply","t":"apply(stemmer: NCSemanticStemmer, parser: NCTokenParser, macros: Map[String, String], elements: List[NCSemanticElement]): NCSemanticEntityParser","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser$","k":"def"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser$.html#apply-4cc","e":false,"n":"apply","t":"apply(stemmer: NCSemanticStemmer, parser: NCTokenParser, elements: List[NCSemanticElement]): NCSemanticEntityParser","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser$","k":"def"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser$.html#apply-bc5","e":false,"n":"apply","t":"apply(stemmer: NCSemanticStemmer, parser: NCTokenParser, mdlSrc: String): NCSemanticEntityParser","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser$","k":"def"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser.html#","e":false,"n":"NCSemanticEntityParser","t":"NCSemanticEntityParser(stemmer: NCSemanticStemmer, parser: NCTokenParser, macros: Map[String, String], elements: List[NCSemanticElement], mdlSrcOpt: Option[String]) extends NCEntityParser with LazyLogging","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticEntityParser","k":"class"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticStemmer.html#","e":false,"n":"NCSemanticStemmer","t":"NCSemanticStemmer","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticStemmer","k":"trait"},
{"l":"org/apache/nlpcraft/nlp/parsers/NCSemanticStemmer.html#stem-fffff2ca","e":false,"n":"stem","t":"stem(txt: String): String","d":"org/apache/nlpcraft/nlp/parsers/NCSemanticStemmer","k":"def"}];